---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zulgoproxy
  labels:
    app: zulgoproxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zulgoproxy
  template:
    metadata:
      labels:
        app: zulgoproxy
    spec:
      containers:
        - name: zulgoproxy
          image: localhost/zulgoproxy:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8181
              name: proxy
            - containerPort: 8182
              name: api

---
apiVersion: v1
kind: Service
metadata:
  name: zulgoproxy
spec:
  selector:
    app: zulgoproxy
  ports:
    - name: proxy
      protocol: TCP
      port: 8181         # Service port inside cluster
      targetPort: 8181   # Container port in the Pod
      nodePort: 30181    # External port on the node
    - name: api
      protocol: TCP
      port: 8182         # Service port inside cluster
      targetPort: 8182   # Container port in the Pod
      nodePort: 30182    # External port on the node
  type: NodePort
